### PR TITLE
Support for 1.20.4 version

### PR DESCRIPTION
**Pull request by ricsal1**
Support for 1.20.4 version

### CODE REVIEW

**Comment by PureGero** [comment]
Thank you!

**Comment by ricsal1** [comment]
> Thank you!

You are welcome m8.
Working on 1.20.6

**Comment by PureGero** [comment]
Whoops, I already added 1.20.6 support

**Comment by ricsal1** [comment]
> Whoops, I already added 1.20.6 support

where did you find the documentation for the new packetIds?

**Comment by PureGero** [comment]
> > Whoops, I already added 1.20.6 support
> 
> where did you find the documentation for the new packetIds?

https://wiki.vg/Pre-release_protocol

It says it's only updated to 24w13a, but they appear to work fine with 1.20.6

**Comment by ricsal1** [comment]
> > > Whoops, I already added 1.20.6 support
> > 
> > 
> > where did you find the documentation for the new packetIds?
> 
> https://wiki.vg/Pre-release_protocol
> 
> It says it's only updated to 24w13a, but they appear to work fine with 1.20.6

Tested it and is not working on my system. What server did you use?

**Comment by PureGero** [comment]
> Tested it and is not working on my system. What server did you use?

Purpur 1.20.6

**Pull request merged**
